project_id = "cduuixhbxagoooinanwq"

[functions.log-auth-event]
verify_jwt = true

[functions.scan-attachment]
verify_jwt = true

[functions.admin-invite-user]
verify_jwt = true

[functions.admin-user-actions]
verify_jwt = true
